### ISSUE TITLE
Filter game list for (manual) categorization

### ISSUE THREAD

**Issue by Knopfdruckoffizier** [rallion/depressurizer#12]
Option would allow the user to filter the displayed game list with a simple text input box based on the game title (like it's possible in the steam library).

Example:
Filter: "Beta"
Results displayed:
Left 4 Dead 2 Beta
Nexuiz Beta
Rising Storm Beta
...

In the next step this could also be used as a condition for auto categorization and could then be even more useful for the user.

**Comment by rallion** [comment]
added for next release.
