### ISSUE TITLE
Some games with tags are not scraped

### ISSUE THREAD

**Issue by HunterZ** [rallion/depressurizer#15]
For some reason some of the games in my library don't show genres in the database editor, even though there are tags for them on the store page.

Here's an example:
http://store.steampowered.com/app/46410/

**Comment by rallion** [comment]
Avencast has tags, but it doesn't have genres. They're different.

Here's what I'll do: I'll add something that uses user tags as a fallback source of genre information.

If a game has no genres set, but does have tags, then the genre autocategorization routine will use the tags instead. It'll filter them by a genre list, so Avencast's genres would be [Action, RPG, Adventure] and wouldn't include Fantasy or Singleplayer.

**Comment by HunterZ** [comment]
Ah, I saw "added tag-based autocat" in the changelog and assumed it was automatic because I can't find any UI controls or settings to exercise that functionality. Edit: Ah, I see how to do it.

Total War: Shogun 2 is another interesting case. The database editor says its URL is store.steampowered.com/app/34330/ but when I open that, Steam redirects to http://store.steampowered.com/app/201270/

**Comment by rallion** [comment]
I had actually thought that I had dealt with cases like that, but it turns out that I made a logic mistake. Next version will properly categorize app 34330 as a Strategy game.

**Comment by rallion** [comment]
all fixed up for next release.
