### ISSUE TITLE
Installed games not saving in manual categories

### ISSUE THREAD

**Issue by greymane98** [rallion/depressurizer#17]
Depressurizer shows the games as I have set them up, with manual categories (i.e. Beaten, Want to Beat, Won't play, etc) and exports cleanly.

When Steam loads however, any games that are installed are not recognizing category set in depressurizer and are showing as uncategorized.  

This was working until recently.  Running v 0.6.

**Comment by rallion** [comment]
I can't duplicate this at all.

Are you sure you're still exiting Steam, then exporting, then restarting Steam?

Is it really only the installed games? Uninstalled games categorize normally? That would make me think that it might be a Steam bug: Depressurizer can't even tell if a game is installed or not so it treats all games identically.

Are you using the release version of Steam or the beta? I've tried duplicating with both, but knowing which you're using might make it easier to find the source of the problem.

**Comment by greymane98** [comment]
Yes, I've exited Steam and restarted several times.  Reloaded and rerun Depressurizer and exported specifically as well as saving profile (just in case).  
Yes it is only installed games and I do suspect something has changed on Steam's end.  I am in the Family Sharing and Steaming Betas....so it may be one of those causing the issue.  I have been in both several months though and this just occurred in the last few days.

Date: Sun, 2 Nov 2014 11:40:55 -0800

**Comment by greymane98** [comment]
I have an idea what may be an issue...and it may be due to family sharing of library.  When my wife sorts my account (on her computer) by only installed, I am wondering if that is effecting what I see on my system.  I will test this and get back to you.

Date: Sun, 2 Nov 2014 11:40:55 -0800

**Comment by greymane98** [comment]
Well I am running out of ideas.
Wife had put her laptop to display only installed games and then went offline.  Since family sharing is on my account, I thought maybe this was doing something to my listing on my machine.  But after reconnecting hers and showing the entire library, it still shows them in the categories as they should be.
But on my machine, all the installed games have lost their categories.  
My Steam library is spread over 3 drives now...is it possible the organization file is no longer in the Steam root drive?  Even when I set a category on Steam now, as soon as I exit and restart, the category is lost and it throws it back under the "Games" listing.  I just have the listing sorted by games...when I change to uncategorized, it still shows all the items that have categories in Depressurizer.  When I Import config file, it shows the categories are still there...
This has to be a Steam issue, but I can't believe I am the only one having the problem.

Date: Sun, 2 Nov 2014 11:40:55 -0800

**Comment by greymane98** [comment]
Well Steam did an update today and the issue disappeared.  Looks like it was an issue with something in the beta that temporarily broke categories.  It is working now.
