### ISSUE TITLE
Feature/Idea: Categorization of trading cards and achievements (sorry for being so lazy)

### ISSUE THREAD

**Issue by Sleazus** [rallion/depressurizer#20]
Pretty much self explanitory.

Just another couple of categories for trading cards and achievements.

Preferably seperately.

Cheers

**Comment by rallion** [comment]
You can do this already. You need to use a "Store Flags" AutoCat.

Go to the Edit AutoCats dialog (Ctrl-T) to create one.

**Comment by Sleazus** [comment]
Thank you very much sir :-)

And well done on a fantastic program
