### ISSUE TITLE
Some games not auto-categorized 

### ISSUE THREAD

**Issue by CorruptComputer** [rallion/depressurizer#21]
105430 - Age of Empires Online
42710 - Call of Duty: Black Ops - Multiplayer
232210 - Chivalry BETA
228200 - Company of Heroes (New Steam Edition)
28050 - Deus Ex: Human Revolution
205790 - Dota 2 Test
212220 - Dungeon Fighter Online
203190 - Evolve [Closed Beta]
267110 - Kingdoms Rise Test
223530 - Left 4 Dead 2 Beta
47830 - Medal of Honor(TM) Multiplayer
43160 - Metro: Last Light
203850 - Microsoft Flight
222710 - Music Creator 6 Touch
36630 - Rusty Hearts
34270 - SEGA Genesis & Mega Drive Classics
208610 - Skullgirls ∞Endless Beta∞
241070 - SONAR X3

I noticed that a lot of these are games that come with a base game, but do not have a store page for themselves. Some of these are also games that are not available on steam anymore, could you make them not show up in the list? Also some of these are beta versions of games, could those be categorized in their own category, along with the categories for the base game.

**Comment by rallion** [comment]
There's not really all that much more that I can do with any of these at this point. If the game has no store page, the genre auto-categorizer will check to see if the game has a parent app specified. If it does, it will fall back and assign the genres for that parent app. Most games, even games that you would think should have a parent app specified, do not.

There are also games (Like Medal of Honor Multiplayer) that have a store page, but have no genres specified. The current version has an option to fall back to tags at that point.

I can't really think of a sensible way to automatically hide any more games from the list. Should I hide all games that have a store page, but no genres? What if they have tags or reviews that can be used with other categorization options? What if they were removed from the Steam store around 2013, which means that they might have genres in the database, but no tags? There are just too many cases to cover and nobody would agree on what options would be useful.

I also can't really hide betas. There's no beta flag for me to check, and looking for "beta" in the app name will result in false positives AND false negatives.

You can manually hide games in Depressurizer by just deleting them from the list. By default, this will ignore them going forward, unless you un-ignore them in your profile settings.

**Comment by CorruptComputer** [comment]
- Make an auto-hide list of games, and put games on it that are no longer available on steam. 
- With the DB editor I can manually add parents, you could add them in code so that they grab the tags by default.
