### ISSUE TITLE
Single Category Mode will assign multiple categories

### ISSUE THREAD

**Issue by rauvagol** [rallion/depressurizer#28]
When using the auto-category mode there appears to be no difference if single-category mode is enabled or disabled, and games will get the same categories either way. (i.e.  Dark Souls II will be categorized as both action and rpg, which is more than a single category)

**Comment by rallion** [comment]
This is as intended. Single category mode only applies to manual categorization in the editor.

You can set up a genre categorization rule that only uses the first genre, however. Just set "Maximum categories to assign" to 1.
