### ISSUE TITLE
Database is out of date

### ISSUE THREAD

**Issue by CorruptComputer** [rallion/depressurizer#37]
Hasn't been updated in 5 months, and many games have been released since then. The auto categories are not working properly because of this.

**Comment by Theo47** [comment]
You have to manually update the database. Just go to Tools->Database Editor select the games you want to update (or just select all of them) and press Scrape Selected.

**Comment by Aiadan** [comment]
I'm having a related problem. The database is up to date, the games are in correct genres in the database editor. The auto-categorize as genre however, doesn't categorize any of the games. Other autocats work fine.

**Comment by Bigfootmech** [comment]
It might be possible to set this to be automatic (ie: it finds an unscraped game, and tried to update it?)

Would that be useful?

**Comment by Theo47** [comment]
It already does that for unscraped games. If you try to autocategorize an unscraped game you would get a "x games not found in the local database. Check the steam store for these game genres?" dialog box.
This seems to happen on all autocats except autocategorizing by user score. Perhaps oversight?

But it won't try to auto update games that haven't been updated for a long time.
It could be useful to have that option too.
Perhaps a dialog box similar to what you get on unscraped games and a setting on the options menu to choose after how many days it will ask to update a game.

**Comment by Bigfootmech** [comment]
I'd look at this, but rallion's not merging my download settings stuff yet, so not sure if he's active etc :(

Also, I don't know why the dev branch hasn't been merged in to master, so I don't know which branch it's safe to work from

**Comment by CorruptComputer** [comment]
@Bigfootmech I think master is the stable branch, and dev is where everything goes to be tested. I might be wrong though.

**Comment by Bigfootmech** [comment]
I kind of get that, but I don't know who tests it. Or why it hasn't been merged back to master after 7 months (and why people's commits from the stable/clean branch are being rejected)

**Comment by Theo47** [comment]
The following is guesswork on my part:
From a quick look at rejected pulls i'd say that the main reason seems to be conflicts with the dev branch.
For that reason i'd also suggest working with the dev branch instead of the main.
Most of the commits on the dev branch seem to be about Automode so he may be waiting for that feature to be completed before he merges dev back to master.

**Comment by Bigfootmech** [comment]
I saw that too, but it doesn't seem like that's gonna be moving on any time soon.

If people wanna add stuff, it'll make merging difficult.

Plus, I don't know what's on the dev branch that shouldn't be in master yet (partially complete feautres), or if they're visible as broken features to users

**Comment by Theo47** [comment]
I only used the dev branch build briefly but i think it is only partially complete features so there shouldn't be any harm on merging the master and dev branches.

I guess you could try suggesting it (merging the branches) but as you said rallion has been inactive so you might have to wait for some time before you get a response.

**Comment by Bigfootmech** [comment]
ok, cheers :)

**Comment by Theo47** [comment]
The automatic-helper branch also differs in a few commits with the dev branch so if you plan to make any changes you may want to merge those 2 branches first to get the latest latest version.

**Comment by Bigfootmech** [comment]
The only thing I'm worried about there is if there are UI changes, but the underlying changes aren't complete, or worse, break/crash the program in some way.

**Comment by Theo47** [comment]
Well after using it i can say that there are some (minor) UI changes but nothing is broken so it is safe to work with that branch (automatic-helper).
Also the auto-mode seems to be completed.

So to avoid any conflicts i'd now suggest to work with the automatic-helper branch.
You can optionally merge the dev branch to the automatic-helper branch. The commits on the dev branch seem easy to merge so it shouldnt matter whether you do it now or later.

**Comment by Bigfootmech** [comment]
Okidoke. I'll do that when I get home then.

Let's see how much I can break this before Rallion comes back ;)
