### ISSUE TITLE
Games not being assigned categories

### ISSUE THREAD

**Issue by Camarron** [rallion/depressurizer#39]
I have over 500 games, the summer sale pushing me over 500 only recently, and as soon as I hit over 500 I have about 98 games that have had their categories erased in the steam client. When I open depressurizer they are all still categorized. I use the Store Tags option most often and the other Auto-Cat options don't work either.

**Comment by Bigfootmech** [comment]
Have you tried save profile/export config file with steam closed, then opening steam up again?

**Comment by Camarron** [comment]
Shortly after I posted that, the issue became fixed. Steam doesn't have store pages for about 20 of my games still, so those are still generically categorized, but the rest was a steam side issue due to the massive traffic of the summer sale I believe.
