### ISSUE TITLE
Updating from Local files Unexpected character

### ISSUE THREAD

**Issue by exmex** [rallion/depressurizer#47]
Error updating from local files:
Unexpected character '7' found when expecting key.

Pretty much says what it does.

When I open depressurizer it gives me that error.

Here is the log btw :diamond_shape_with_a_dot_inside: 

> 14:28:36.558735 -  ERR: Exception when performing local update.
>   Depressurizer.ParseException: Unexpected character '7' found when expecting key.
>   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
>   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
>   at Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
>   at Depressurizer.PackageInfo.LoadPackages(String path)
>   at Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps)
>   at Depressurizer.FormMain.UpdateLibrary()

**Comment by Theo47** [comment]
This error happens while reading from <path-to-steam>\Steam\userdata<id-number>\config\localconfig.vdf
The program expects each value to be enclosed in double quotes like [here](http://serv108.serveur-clan.com/autogames/serv1997/Steam/userdata/87234555/config/localconfig.vdf) or [here](http://ns2.gnt-craft.ru/userdata/105663487/config/localconfig.vdf).
Apparently you have a value starting with 7 that isn't enclosed in quotes somewhere in the file.

Do you think you could locate where that happens and post the relevant lines?
Alternatively can you post your localconfig.vdf file? In this case you may want to skim through it and remove any sensitive data first.

**Comment by exmex** [comment]
So the problem is not the localconfig.vdf it's actually the appache\packageinfo.vdf

![Debugging Depressurizer](http://i.imgur.com/3xkI6Kd.png)

![Debugging Depressurizer2](http://i.imgur.com/Z0ATiHT.png)

EDIT:
And it is fixed in your 0.6.3 version.

**Comment by Theo47** [comment]
I see. I missed the PackageInfo.LoadPackages function so i assumed it was VdfFileNode.LoadFromText from a few lines below.

Kinda strange since i never touched any of those functions. But all's well that ends well.

Edit: Apparently rallion had fixed it in his dev branch.
Edit2: https://github.com/rallion/depressurizer/pull/32

**Comment by exmex** [comment]
Alright :). I'm just using yours now. This is kinda old :P
