### ISSUE TITLE
AutoCat/Tag Option: Narrow by number of players

### ISSUE THREAD

**Issue by 00face** [rallion/depressurizer#52]
First I want to say thank you very much for all your hard work. My library definitely is far more sane than it was. That said I do need one last thing if you could and the main goal of seeking your application out in the first place.

Could you please add the ability to create separate categories for the following:

Narrow by number of players:
 Single-player
 Multi-player
 Cross-Platform Multiplayer
 Co-op
 Local Co-op

For me my biggest gripe with my library is trying to figure out what I can actually play with someone, or even gift them for that purpose.

Respectfully,
7777 Tʜɛ Ӻ๑๛∂ß¡╬ξrร
http://steamcommunity.com/id/00face/

**Comment by Theo47** [comment]
That is already possible. Just go to Profile->edit autocats, create an autocat by flags and check the flags you want

**Comment by 00face** [comment]
Right you are!!!! Thank you so much! WHERE DO I DONATE!!!!+?
