### ISSUE TITLE
Option to Use Other User-Defined Tags

### ISSUE THREAD

**Issue by Torakusu** [rallion/depressurizer#58]
Is it possible to give us an option to include other user-defined tags for auto-cat? For example: Tower Defense, Sci-fi, Visual Novel... Thanks.

**Comment by Theo47** [comment]
Can't you already do that? 
If you go Profile->Edit Autocats, you can create an autocat that categorizes games by store tags, including those you mentioned.

**Comment by Torakusu** [comment]
OH, there we go.  Thanks!
