### ISSUE TITLE
Unexpected character '53' found when expecting key.

### ISSUE THREAD

**Issue by BSE97** [rallion/depressurizer#63]
Hi,

everytime I start despressurizer I get the following error: Unexpected character '53' found when expecting key.

Here is what is written in the Log:
13:24:12.391603 -  ERR: Exception when performing local update.
Depressurizer.ParseException: Unexpected character '53' found when expecting key.
   bei Depressurizer.VdfFileNode.LoadFromBinary(BinaryReader stream, Int64 streamLength)
   bei Depressurizer.PackageInfo.LoadPackages(String path)
   bei Depressurizer.GameList.UpdateGameListFromOwnedPackageInfo(Int64 accountId, SortedSet`1 ignored, AppTypes includedTypes, Int32& newApps)
   bei Depressurizer.FormMain.UpdateLibrary()

**Comment by PinoTucana** [comment]
Same, I receive a error: 51

**Comment by thunderpants** [comment]
rallion/depressurizer
and the fork Theo47/depressurizer both need some TLC.

**Comment by ibigfire** [comment]
And I get unexpected character 57.

**Comment by Zhuinden** [comment]
Fixed in https://github.com/Theo47/depressurizer/issues/64#issuecomment-257153102

**Comment by BSE97** [comment]
This fixed it.
Thank you
