### ISSUE TITLE
Error updating from local files: Unexpected character '10'' found when expecting key

### ISSUE THREAD

**Issue by kaizacorp** [rallion/depressurizer#65]
I get this error when trying to update from local files. However, when I disable using local files and try to update from online nothing happens and then both checkboxes become deselected in the options. 

On Windows 7 Ultimate 64 bit.

**Comment by PinoTucana** [comment]
It's like most users have this issue now.
And the error number is random appears.
But seems it can be ignored, depressurizer itself is all function works.

**Comment by kaizacorp** [comment]
Depressurizer can still organize my games, but it can only find 244 out of 294.

**Comment by Zhuinden** [comment]
Fixed in https://github.com/Theo47/depressurizer/issues/64#issuecomment-257153102

**Comment by kaizacorp** [comment]
Thanks, got it working now.
