### ISSUE TITLE
Not loading all the games in the library

### ISSUE THREAD

**Issue by khlj** [rallion/depressurizer#76]
I know this issue has been mentioned, however I am using the latest version (0.7.14) of Depressurizer and the same issue  pops up.

It pops up the error message "No game data found."

And when it loads my steam profile, it only shows a fraction of the games in my library.

I have several steam libraries in different drives by the way, if that might be related...

**Comment by khlj** [comment]
Looks like one solution would be to,

1. Add all of the games into a named category, say "a"

2. Exit out of steam

3. Start Depressurizer, create a new profile. Start steam.

4. All games loaded.

**Comment by DeMyztikX** [comment]
@hshin23 have you tried Theo's version https://github.com/Theo47/depressurizer

This version isn't maintained any more but Theo has fixed a lot of issues I was having in his fork.
